version: 2
defaults: &defaults
  working_directory: ~/code
  docker:
    - image: circleci/android:api-28-alpha
  resource_class: large
  environment:
    JVM_OPTS: -Xmx2048m -XX:ParallelGCThreads=2 -XX:ConcGCThreads=2 -XX:ParallelGCThreads=2 -Djava.util.concurrent.ForkJoinPool.common.parallelism=2
    GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.jvmargs='-Xmx2048m -XX:MaxPermSize=512m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8'"
    _JAVA_OPTIONS: "-Xmx1500m -XX:ParallelGCThreads=2 -XX:ConcGCThreads=2 -XX:ParallelGCThreads=2 -Djava.util.concurrent.ForkJoinPool.common.parallelism=2"

jobs:
  build_master:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "sample/build.gradle" }}
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "sample/build.gradle" }}
      - run:
          name: Run assemble
          no_output_timeout: 30m
#           why set gradle options? https://youtrack.jetbrains.com/issue/KT-17601
          command: ./gradlew sample:assembleDebug
      - run:
          name: Run Tests
          no_output_timeout: 60m
          command: ./gradlew test
      - run:
          name: Run Lint
          no_output_timeout: 30m
          command: ./gradlew lint
      - store_artifacts:
          path: sample/build/reports
          destination: reports
      - store_artifacts:
          path: sample/build/outputs/apk/debug
          destination: apks
      - store_test_results:
          path: sample/build/test-results
      - persist_to_workspace:
          root: ~/code
          paths:
            - .
workflows:
  version: 2
  master:
    jobs:
      - build_master:
